# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dgarcez- < dgarcez-@student.42lisboa.com > +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/01/05 18:14:34 by dgarcez-          #+#    #+#              #
#    Updated: 2026/01/13 15:26:19 by dgarcez-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = megaphone	

CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98

SRCS =	megaphone.cpp

OBJ_FILES =  $(SRCS:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJ_FILES)
	$(CC) $(CFLAGS) $(OBJ_FILES) -o $(NAME)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ_FILES)

fclean: clean
	rm -f $(NAME)

re: fclean all